FROM python:3.9-slim-buster

#RUN pip install -U pip
#RUN pip install pipenv 

ARG WORKDIR=/app
WORKDIR ${WORKDIR}

COPY [ "Pipfile", "Pipfile.lock", "./" ]

RUN pipenv install --system --deploy

COPY [ "predict.py", "notebooks/models/model_log_reg.bin", "./" ]

EXPOSE 5000

ENTRYPOINT [ "gunicorn", "--bind=0.0.0.0:5000", "predict:${WORKDIR}" ]
