datasets:
  penguins:
    column_mapping:
      categorical_features:
        - 'species'
        - 'island'
      numerical_features:
        - 'bill_length_mm'
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
    reference_file: ./datasets/pengiuns.parquet
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 5
